name: Version bump

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Bump version based on merge size
        env:
          FILE_THRESHOLD: "10"
          LINE_THRESHOLD: "500"
        run: |
          python .github/scripts/bump_version.py
      - name: Commit and push changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: bump version after merge"
          git push
